FROM gcr.io/distroless/base

LABEL maintainer="Nikhil Bhatia <rite2nikhil@gmail.com>"

ADD ./kubernetes-policy-controller /bin/kubernetes-policy-controller

ENTRYPOINT ["kubernetes-policy-controller"]
