//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	unversioned "github.com/open-policy-agent/gatekeeper/apis/expansion/unversioned"
	v1beta1 "github.com/open-policy-agent/gatekeeper/apis/status/v1beta1"
	match "github.com/open-policy-agent/gatekeeper/pkg/mutation/match"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*GeneratedGVK)(nil), (*unversioned.GeneratedGVK)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GeneratedGVK_To_unversioned_GeneratedGVK(a.(*GeneratedGVK), b.(*unversioned.GeneratedGVK), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.GeneratedGVK)(nil), (*GeneratedGVK)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_GeneratedGVK_To_v1alpha1_GeneratedGVK(a.(*unversioned.GeneratedGVK), b.(*GeneratedGVK), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateExpansion)(nil), (*unversioned.TemplateExpansion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateExpansion_To_unversioned_TemplateExpansion(a.(*TemplateExpansion), b.(*unversioned.TemplateExpansion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.TemplateExpansion)(nil), (*TemplateExpansion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_TemplateExpansion_To_v1alpha1_TemplateExpansion(a.(*unversioned.TemplateExpansion), b.(*TemplateExpansion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateExpansionList)(nil), (*unversioned.TemplateExpansionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateExpansionList_To_unversioned_TemplateExpansionList(a.(*TemplateExpansionList), b.(*unversioned.TemplateExpansionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.TemplateExpansionList)(nil), (*TemplateExpansionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_TemplateExpansionList_To_v1alpha1_TemplateExpansionList(a.(*unversioned.TemplateExpansionList), b.(*TemplateExpansionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateExpansionSpec)(nil), (*unversioned.TemplateExpansionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateExpansionSpec_To_unversioned_TemplateExpansionSpec(a.(*TemplateExpansionSpec), b.(*unversioned.TemplateExpansionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.TemplateExpansionSpec)(nil), (*TemplateExpansionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_TemplateExpansionSpec_To_v1alpha1_TemplateExpansionSpec(a.(*unversioned.TemplateExpansionSpec), b.(*TemplateExpansionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TemplateExpansionStatus)(nil), (*unversioned.TemplateExpansionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TemplateExpansionStatus_To_unversioned_TemplateExpansionStatus(a.(*TemplateExpansionStatus), b.(*unversioned.TemplateExpansionStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*unversioned.TemplateExpansionStatus)(nil), (*TemplateExpansionStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_unversioned_TemplateExpansionStatus_To_v1alpha1_TemplateExpansionStatus(a.(*unversioned.TemplateExpansionStatus), b.(*TemplateExpansionStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_GeneratedGVK_To_unversioned_GeneratedGVK(in *GeneratedGVK, out *unversioned.GeneratedGVK, s conversion.Scope) error {
	out.Group = in.Group
	out.Version = in.Version
	out.Kind = in.Kind
	return nil
}

// Convert_v1alpha1_GeneratedGVK_To_unversioned_GeneratedGVK is an autogenerated conversion function.
func Convert_v1alpha1_GeneratedGVK_To_unversioned_GeneratedGVK(in *GeneratedGVK, out *unversioned.GeneratedGVK, s conversion.Scope) error {
	return autoConvert_v1alpha1_GeneratedGVK_To_unversioned_GeneratedGVK(in, out, s)
}

func autoConvert_unversioned_GeneratedGVK_To_v1alpha1_GeneratedGVK(in *unversioned.GeneratedGVK, out *GeneratedGVK, s conversion.Scope) error {
	out.Group = in.Group
	out.Version = in.Version
	out.Kind = in.Kind
	return nil
}

// Convert_unversioned_GeneratedGVK_To_v1alpha1_GeneratedGVK is an autogenerated conversion function.
func Convert_unversioned_GeneratedGVK_To_v1alpha1_GeneratedGVK(in *unversioned.GeneratedGVK, out *GeneratedGVK, s conversion.Scope) error {
	return autoConvert_unversioned_GeneratedGVK_To_v1alpha1_GeneratedGVK(in, out, s)
}

func autoConvert_v1alpha1_TemplateExpansion_To_unversioned_TemplateExpansion(in *TemplateExpansion, out *unversioned.TemplateExpansion, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TemplateExpansionSpec_To_unversioned_TemplateExpansionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TemplateExpansionStatus_To_unversioned_TemplateExpansionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TemplateExpansion_To_unversioned_TemplateExpansion is an autogenerated conversion function.
func Convert_v1alpha1_TemplateExpansion_To_unversioned_TemplateExpansion(in *TemplateExpansion, out *unversioned.TemplateExpansion, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateExpansion_To_unversioned_TemplateExpansion(in, out, s)
}

func autoConvert_unversioned_TemplateExpansion_To_v1alpha1_TemplateExpansion(in *unversioned.TemplateExpansion, out *TemplateExpansion, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_unversioned_TemplateExpansionSpec_To_v1alpha1_TemplateExpansionSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_unversioned_TemplateExpansionStatus_To_v1alpha1_TemplateExpansionStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_TemplateExpansion_To_v1alpha1_TemplateExpansion is an autogenerated conversion function.
func Convert_unversioned_TemplateExpansion_To_v1alpha1_TemplateExpansion(in *unversioned.TemplateExpansion, out *TemplateExpansion, s conversion.Scope) error {
	return autoConvert_unversioned_TemplateExpansion_To_v1alpha1_TemplateExpansion(in, out, s)
}

func autoConvert_v1alpha1_TemplateExpansionList_To_unversioned_TemplateExpansionList(in *TemplateExpansionList, out *unversioned.TemplateExpansionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]unversioned.TemplateExpansion)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_TemplateExpansionList_To_unversioned_TemplateExpansionList is an autogenerated conversion function.
func Convert_v1alpha1_TemplateExpansionList_To_unversioned_TemplateExpansionList(in *TemplateExpansionList, out *unversioned.TemplateExpansionList, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateExpansionList_To_unversioned_TemplateExpansionList(in, out, s)
}

func autoConvert_unversioned_TemplateExpansionList_To_v1alpha1_TemplateExpansionList(in *unversioned.TemplateExpansionList, out *TemplateExpansionList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]TemplateExpansion)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_unversioned_TemplateExpansionList_To_v1alpha1_TemplateExpansionList is an autogenerated conversion function.
func Convert_unversioned_TemplateExpansionList_To_v1alpha1_TemplateExpansionList(in *unversioned.TemplateExpansionList, out *TemplateExpansionList, s conversion.Scope) error {
	return autoConvert_unversioned_TemplateExpansionList_To_v1alpha1_TemplateExpansionList(in, out, s)
}

func autoConvert_v1alpha1_TemplateExpansionSpec_To_unversioned_TemplateExpansionSpec(in *TemplateExpansionSpec, out *unversioned.TemplateExpansionSpec, s conversion.Scope) error {
	out.ApplyTo = *(*[]match.ApplyTo)(unsafe.Pointer(&in.ApplyTo))
	out.TemplateSource = in.TemplateSource
	if err := Convert_v1alpha1_GeneratedGVK_To_unversioned_GeneratedGVK(&in.GeneratedGVK, &out.GeneratedGVK, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TemplateExpansionSpec_To_unversioned_TemplateExpansionSpec is an autogenerated conversion function.
func Convert_v1alpha1_TemplateExpansionSpec_To_unversioned_TemplateExpansionSpec(in *TemplateExpansionSpec, out *unversioned.TemplateExpansionSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateExpansionSpec_To_unversioned_TemplateExpansionSpec(in, out, s)
}

func autoConvert_unversioned_TemplateExpansionSpec_To_v1alpha1_TemplateExpansionSpec(in *unversioned.TemplateExpansionSpec, out *TemplateExpansionSpec, s conversion.Scope) error {
	out.ApplyTo = *(*[]match.ApplyTo)(unsafe.Pointer(&in.ApplyTo))
	out.TemplateSource = in.TemplateSource
	if err := Convert_unversioned_GeneratedGVK_To_v1alpha1_GeneratedGVK(&in.GeneratedGVK, &out.GeneratedGVK, s); err != nil {
		return err
	}
	return nil
}

// Convert_unversioned_TemplateExpansionSpec_To_v1alpha1_TemplateExpansionSpec is an autogenerated conversion function.
func Convert_unversioned_TemplateExpansionSpec_To_v1alpha1_TemplateExpansionSpec(in *unversioned.TemplateExpansionSpec, out *TemplateExpansionSpec, s conversion.Scope) error {
	return autoConvert_unversioned_TemplateExpansionSpec_To_v1alpha1_TemplateExpansionSpec(in, out, s)
}

func autoConvert_v1alpha1_TemplateExpansionStatus_To_unversioned_TemplateExpansionStatus(in *TemplateExpansionStatus, out *unversioned.TemplateExpansionStatus, s conversion.Scope) error {
	out.ByPod = *(*[]v1beta1.MutatorPodStatusStatus)(unsafe.Pointer(&in.ByPod))
	return nil
}

// Convert_v1alpha1_TemplateExpansionStatus_To_unversioned_TemplateExpansionStatus is an autogenerated conversion function.
func Convert_v1alpha1_TemplateExpansionStatus_To_unversioned_TemplateExpansionStatus(in *TemplateExpansionStatus, out *unversioned.TemplateExpansionStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_TemplateExpansionStatus_To_unversioned_TemplateExpansionStatus(in, out, s)
}

func autoConvert_unversioned_TemplateExpansionStatus_To_v1alpha1_TemplateExpansionStatus(in *unversioned.TemplateExpansionStatus, out *TemplateExpansionStatus, s conversion.Scope) error {
	out.ByPod = *(*[]v1beta1.MutatorPodStatusStatus)(unsafe.Pointer(&in.ByPod))
	return nil
}

// Convert_unversioned_TemplateExpansionStatus_To_v1alpha1_TemplateExpansionStatus is an autogenerated conversion function.
func Convert_unversioned_TemplateExpansionStatus_To_v1alpha1_TemplateExpansionStatus(in *unversioned.TemplateExpansionStatus, out *TemplateExpansionStatus, s conversion.Scope) error {
	return autoConvert_unversioned_TemplateExpansionStatus_To_v1alpha1_TemplateExpansionStatus(in, out, s)
}
